[build]
  command = "npm install && npm run build"
  functions = "functions"
  publish = "build"

[[headers]]
for = "*.wasm"
[headers.values]
Content-Type = "application/wasm"


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/app/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
  
[functions]
  node_bundler = "esbuild"
